"""
Django settings for student_violation_system project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1m=i!+(*d1tu=a)jwdmg__z=v(v!#ll69!@mdlx7&)@!c4uyz5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "jazzmin",  # Jazzmin MUST be before django.contrib.admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "channels",  # WebSocket support for realtime features (temporarily commented)
    "violations",  # Add the violations app
]

# =============================================================================
# JAZZMIN SETTINGS - Modern Admin Panel Theme
# Documentation: https://django-jazzmin.readthedocs.io/
# =============================================================================

JAZZMIN_SETTINGS = {
    "site_title": "UDM OSA Management System",
    "site_header": "UDM OSA Management System",
    "site_brand": "UDM OSA",
    "site_logo": "violations/images/chmsu_logo.png",
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Welcome to the UDM Office of Student Affairs Management System",
    "copyright": "Universidad de Manila - Office of Student Affairs",
    "search_model": [
        "violations.Student",
        "violations.User",
        "violations.Violation",
    ],
    "user_avatar": None,
    "topmenu_links": [
        {
            "name": "Home",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },
        {
            "name": "OSA Coordinator Dashboard",
            "url": "/faculty/dashboard/",
            "new_window": True,
        },
    ],
    "usermenu_links": [
        {
            "model": "auth.user",
        },
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    # Hide Django's built-in authentication management
    # from the main OSA navigation.
    "hide_apps": [
        "auth",
    ],
    # Hide models that are not part of the UDM OSA Coordinator workflow
    "hide_models": [
        "violations.User",
        "violations.OSACoordinator",
        "violations.Staff",
        "violations.Message",
        "violations.ChatMessage",
        "violations.IDConfiscation",
        "violations.ViolationClearance",
        "auth.Group",
    ],
    # Only show the models relevant to the UDM OSA Coordinator
    "order_with_respect_to": [
        "violations.Student",
        "violations.Violation",
        "violations.ApologyLetter",
        "violations.LoginActivity",
        "violations.ViolationType",
        "violations.ViolationDocument",
    ],
    "custom_links": {},
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "violations": "fas fa-gavel",
        "violations.User": "fas fa-user-shield",
        "violations.Student": "fas fa-user-graduate",
        "violations.OSACoordinator": "fas fa-user-tie",
        "violations.Staff": "fas fa-user-tie",
        "violations.Violation": "fas fa-exclamation-triangle",
        "violations.ApologyLetter": "fas fa-envelope-open-text",
        "violations.IDConfiscation": "fas fa-id-card",
        "violations.ViolationClearance": "fas fa-clipboard-check",
        "violations.ViolationDocument": "fas fa-file-alt",
        "violations.LoginActivity": "fas fa-history",
        "violations.Message": "fas fa-comments",
        "violations.ChatMessage": "fas fa-comment-dots",
        "violations.ViolationType": "fas fa-list",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "violations/css/admin_custom.css",
    "custom_js": "violations/js/admin_custom.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "violations.User": "collapsible",
        "violations.Violation": "horizontal_tabs",
        "violations.Student": "horizontal_tabs",
    },
    "language_chooser": False,
}
# Jazzmin UI Tweaks - Customize colors and layout
# Theme based on UDM green colors
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "navbar": "navbar-success navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "student_violation_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "student_violation_system.wsgi.application"
# ASGI_APPLICATION = "student_violation_system.asgi.application"  # Temporarily commented


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Set USE_SQLITE=True to use SQLite, otherwise PostgreSQL
import os

USE_SQLITE = os.environ.get("USE_SQLITE", "False").lower() in ("true", "1", "yes")

if USE_SQLITE:
    # SQLite configuration (portable, built-in with data)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # PostgreSQL configuration (primary database)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "student_tracking_db",
            "USER": "postgres",
            "PASSWORD": "1234",
            "HOST": "localhost",
            "PORT": "5432",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = []
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user uploaded content)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Authentication model & redirects
AUTH_USER_MODEL = "violations.User"

# These reverse names assume the app is included with namespace 'violations'
LOGIN_URL = "violations:auth_login"
LOGIN_REDIRECT_URL = "violations:route_dashboard"
LOGOUT_REDIRECT_URL = "/admin/login/"  # Redirect to admin login after logout

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Channels (development: in-memory layer; for production use Redis)
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     }
# }
