# Generated by Django 5.2.7 on 2025-11-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/students/"
            ),
        ),
    ]
