# Generated by Django 5.2.7 on 2025-11-03 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0002_alter_student_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_at", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("minor", "Minor"), ("major", "Major")], max_length=10
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("witness_statement", models.TextField(blank=True)),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True, null=True, upload_to="violations/evidence/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="violations_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="violations.student",
                    ),
                ),
            ],
        ),
    ]
