# Generated by Django 5.2.7 on 2025-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0006_apologyletter_idconfiscation_staffverification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_by_receiver",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_by_sender",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
