# Generated by Django 5.2.7 on 2025-12-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0008_rename_faculty_to_osa_coordinator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="room",
            field=models.CharField(default="staff-osa", max_length=100),
        ),
    ]
