# Generated by Django 5.2.7 on 2025-12-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0009_update_chat_room_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.CharField(
                blank=True, help_text="Home address", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.CharField(
                blank=True, help_text="e.g., A, B, C or 1, 2, 3", max_length=20
            ),
        ),
    ]
