# Generated by Django 5.2.7 on 2025-12-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0010_add_student_address_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="section",
        ),
    ]
