# Generated by Django 5.2.7 on 2025-12-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0011_remove_student_address_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="apologyletter",
            name="letter_campus",
            field=models.CharField(blank=True, help_text="Campus name", max_length=200),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="letter_date",
            field=models.CharField(
                blank=True, help_text="Date on the letter", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="letter_full_name",
            field=models.CharField(
                blank=True, help_text="Student full name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="letter_home_address",
            field=models.CharField(
                blank=True, help_text="Home address", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="letter_printed_name",
            field=models.CharField(
                blank=True, help_text="Printed name for signature", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="letter_program",
            field=models.CharField(
                blank=True, help_text="Program, Major, Year & Section", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="letter_violations",
            field=models.TextField(blank=True, help_text="Specific violation/s"),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="signature_data",
            field=models.TextField(
                blank=True, help_text="Base64 encoded signature image"
            ),
        ),
        migrations.AlterField(
            model_name="apologyletter",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="apology_letters/%Y/%m/"
            ),
        ),
    ]
