# Generated by Django 5.2.7 on 2025-12-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0013_staffalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffalert",
            name="meeting_notes",
            field=models.TextField(
                blank=True, help_text="Additional notes for the meeting"
            ),
        ),
    ]
