# Generated by Django 5.2.7 on 2025-12-19 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0014_staffalert_meeting_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViolationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/description of the violation", max_length=255
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("major", "Major Offense (MO)"),
                            ("minor", "Minor Offense (MiO)"),
                        ],
                        default="minor",
                        max_length=10,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Optional violation code for reference",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description or guidelines"
                    ),
                ),
                (
                    "penalty",
                    models.TextField(
                        blank=True, help_text="Standard penalty for this violation type"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive violations won't appear in selection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Violation Type",
                "verbose_name_plural": "Violation Types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="violation",
            name="violation_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific violation type from the catalog",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="violations",
                to="violations.violationtype",
            ),
        ),
    ]
