# Generated by Django 5.2.7 on 2025-12-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0015_add_violation_type_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="violationclearance",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="violationclearance",
            name="cleared_by",
        ),
        migrations.RemoveField(
            model_name="violationclearance",
            name="student",
        ),
        migrations.RemoveField(
            model_name="violationclearance",
            name="violation",
        ),
        migrations.AddField(
            model_name="violation",
            name="reported_by_guard",
            field=models.CharField(
                blank=True,
                help_text="Guard code if reported by security guard (Guard1, Guard2, Guard3)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="IDConfiscation",
        ),
        migrations.DeleteModel(
            name="ViolationClearance",
        ),
    ]
