# Generated by Django 5.2.7 on 2025-12-24 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0016_add_reported_by_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="apologyletter",
            name="community_service_completed",
            field=models.BooleanField(
                default=False, help_text="Has the student completed community service"
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="formator_photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo evidence of community service completion",
                null=True,
                upload_to="apology_letters/formator_photos/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="formator_remarks",
            field=models.TextField(blank=True, help_text="Formator notes/comments"),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="formator_signature",
            field=models.TextField(
                blank=True, help_text="Base64 encoded formator signature"
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="formator_signed_at",
            field=models.DateTimeField(
                blank=True, help_text="When formator signed", null=True
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="formator_status",
            field=models.CharField(
                choices=[
                    ("not_sent", "Not Sent to Formator"),
                    ("pending", "Pending Formator Review"),
                    ("signed", "Signed by Formator"),
                    ("rejected", "Rejected by Formator"),
                ],
                default="not_sent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="sent_to_formator_at",
            field=models.DateTimeField(
                blank=True, help_text="When staff sent to formator", null=True
            ),
        ),
        migrations.AddField(
            model_name="apologyletter",
            name="sent_to_formator_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="letters_sent_to_formator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
