# Generated by Django 5.2.7 on 2026-01-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0017_add_formator_verification_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                help_text="8-digit student ID number", max_length=8, unique=True
            ),
        ),
    ]
