# Generated by Django 5.2.7 on 2026-01-01 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0018_update_student_id_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                help_text="8-digit student ID number (e.g., 20240001)",
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Student ID must be exactly 8 digits (numbers only).",
                        regex="^\\d{8}$",
                    )
                ],
            ),
        ),
    ]
