# Generated by Django 5.2.7 on 2026-01-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0019_enforce_8digit_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="suffix",
            field=models.CharField(
                blank=True, help_text="Name suffix (Jr., Sr., III, etc.)", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="year_level_assigned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current year level was assigned (for auto-promotion)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAS", "CAS - College of Arts and Sciences"),
                    ("CBMA", "CBMA - College of Business Management and Accountancy"),
                    ("CCS", "CCS - College of Computer Studies"),
                    ("COEd", "COEd - College of Education"),
                    ("CIT", "CIT - College of Industrial Technology"),
                    ("COE", "COE - College of Engineering"),
                ],
                max_length=100,
            ),
        ),
    ]
