# Generated by Django 5.2.7 on 2026-01-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0020_add_student_suffix_and_year_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="apologyletter",
            name="letter_suffix",
            field=models.CharField(
                blank=True,
                help_text="Name suffix (Jr., Sr., III, etc.) - Optional",
                max_length=20,
            ),
        ),
    ]
