# Generated by Django 5.2.7 on 2026-01-05 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0021_add_letter_suffix"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("violation_created", "Created Violation"),
                            ("violation_updated", "Updated Violation"),
                            ("violation_verified", "Verified Violation"),
                            ("violation_dismissed", "Dismissed Violation"),
                            ("apology_reviewed", "Reviewed Apology Letter"),
                            ("apology_approved", "Approved Apology Letter"),
                            ("apology_rejected", "Rejected Apology Letter"),
                            ("apology_revision", "Requested Apology Revision"),
                            ("apology_sent_formator", "Sent to Formator"),
                            ("message_sent", "Sent Message"),
                            ("student_added", "Added Student"),
                            ("meeting_scheduled", "Scheduled Meeting"),
                            ("alert_resolved", "Resolved Alert"),
                            ("apology_submitted", "Submitted Apology Letter"),
                            ("apology_resubmitted", "Resubmitted Apology Letter"),
                            ("profile_updated", "Updated Profile"),
                            ("incident_reported", "Reported Incident"),
                            ("id_confiscated", "Confiscated ID"),
                            ("letter_signed", "Signed Apology Letter"),
                            ("letter_rejected_formator", "Rejected by Formator"),
                            ("violation_reported", "Reported Violation"),
                            ("report_viewed", "Viewed Reports"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the activity"),
                ),
                (
                    "attached_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image attachment for the activity",
                        null=True,
                        upload_to="activity_logs/%Y/%m/",
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "related_apology",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="violations.apologyletter",
                    ),
                ),
                (
                    "related_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="violations.student",
                    ),
                ),
                (
                    "related_violation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="violations.violation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
