# Generated by Django 5.2.7 on 2026-01-05 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0022_add_activity_log_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="formator_code",
            field=models.CharField(
                blank=True,
                help_text="Formator code for formator activities",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="guard_code",
            field=models.CharField(
                blank=True, help_text="Guard code for guard activities", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action (null for guards/formators using code-based login)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
