# Generated by Django 5.2.7 on 2026-01-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0023_add_guard_formator_to_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffalert",
            name="meeting_status",
            field=models.CharField(
                choices=[
                    ("not_scheduled", "Not Scheduled"),
                    ("scheduled", "Scheduled"),
                    ("met", "Met/Completed"),
                    ("expired", "Did Not Meet/Expired"),
                ],
                default="not_scheduled",
                help_text="Current status of the scheduled meeting",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staffalert",
            name="meeting_status_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the meeting status was last updated",
                null=True,
            ),
        ),
    ]
