# Generated by Django 5.2.7 on 2026-01-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0024_add_meeting_status_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TemporaryAccessRequest",
        ),
    ]
