# Generated by Django 5.2.7 on 2026-01-08 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0025_delete_temporaryaccessrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffalert",
            name="dismissed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the alert was dismissed/deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="staffalert",
            name="dismissed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who dismissed this alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dismissed_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
