# Generated by Django 5.2.7 on 2026-01-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0027_add_meeting_deadline"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StaffVerification",
        ),
    ]
